// The vibes, defined as plain objects — add entries with the same shape.

export const themeIds = /** @type {const} */ (['library', 'atelier', 'midnight']);

/** @typedef {typeof themeIds[number]} ThemeId */

export const themes = {
  library: {
    appBg: '#2a1f17',
    chrome: '#ebdcc0',
    sidebar: '#ebdcc0',
    canvas: '#f5ecd9',
    desk: '#1f1610',
    border: '#c9b48e',
    text: '#1f150f',
    textMuted: '#5f4b35',
    chromeText: '#1f150f',
    chromeTextMuted: '#4d3a28',
    chromeTextDim: '#6f5a43',
    activeBg: '#d4a259',
    activeText: '#2a1f17',
    accent: '#8a4f2a',
    fontSerif: '"Iowan Old Style", "Newsreader", "Palatino", "Georgia", serif',
    fontProse: '"Iowan Old Style", "Newsreader", "Palatino", "Georgia", serif',
    fontUi: '"Inter", system-ui, sans-serif',
  },
  atelier: {
    appBg: '#f4f3ee',
    chrome: '#fafaf7',
    sidebar: '#fafaf7',
    canvas: '#ffffff',
    desk: '#ececea',
    border: '#e5e3dc',
    text: '#191815',
    textMuted: '#57534c',
    chromeText: '#191815',
    chromeTextMuted: '#43403a',
    chromeTextDim: '#69645d',
    activeBg: '#f0eee5',
    activeText: '#2c2a26',
    accent: '#2c2a26',
    fontSerif: '"Inter", system-ui, sans-serif',
    fontProse: '"Newsreader", "Charter", "Iowan Old Style", Georgia, serif',
    fontUi: '"Inter", system-ui, sans-serif',
  },
  midnight: {
    /* Deep cool bases so panels read as layers; body text stays near-white for WCAG contrast on every surface. */
    appBg: '#05070c',
    chrome: '#0c111a',
    sidebar: '#0c111a',
    canvas: '#111827',
    desk: '#0b0f17',
    border: '#3d4f6a',
    text: '#f4f7fc',
    textMuted: '#a9b8cc',
    chromeText: '#e8e6e0',
    chromeTextMuted: '#aeb5c4',
    chromeTextDim: '#7f899c',
    activeBg: '#1d4a7a',
    activeText: '#ffffff',
    accent: '#7dd3fc',
    fontSerif: '"Newsreader", "Charter", Georgia, serif',
    fontProse: '"Newsreader", "Charter", Georgia, serif',
    fontUi: '"Inter", system-ui, sans-serif',
  },
};
